id: 9d126822-dcb5-4f43-9bac-bddbadba280d
title: DynamicFPS++ (30 fps)
subtitle: 30fps, Dynamic timestep, with a plethora of fixes.
description: "30fps, Dynamic timestep, with a plethora of fixes.\n- Cutscene Fix\n- Ultrahand fix"
version: 0.5.0
category: 1 # 1: FPS/Performance
game:
  titleId: 0100F2C011586000
  version:
    - 1.0.0
    - 1.1.0
    - 1.1.1
    - 1.1.2
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
    - 2008fac7-32d3-464a-bd96-769e47404755
author:
  - name: ChucksFeedAndSeed, patchanon and somerandompeople
    link: https://gbatemp.net/download/.37996/